### ISSUE TITLE
json errors

### ISSUE THREAD

**Issue by oNIenSis** [tomquirk/realestate-com-au-api#36]
This script was working fine for me yesterday but today it's crashing with errors:
`Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/realestate/simple.py", line 3, in <module>
    listings = api.search(locations=["sydney"], channel="rent")
  File "/home/matt/realestate/src/realestate-com-au-api/realestate_com_au/realestate_com_au.py", line 221, in search
    listings = self._scroll(
  File "/home/matt/.local/lib/python3.9/site-packages/fajita/fajita.py", line 86, in _scroll
    items = items + parse_items(res)
  File "/home/matt/realestate/src/realestate-com-au-api/realestate_com_au/realestate_com_au.py", line 162, in parse_items
    data = res.json()
  File "/home/matt/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
I'm not 100% sure whether this is something I've broken or a realestate.com.au change? I have tried reinstalling python and all the packages, and downgrading versions, but no change.

**Comment by sameermcfc** [comment]
Also getting the same issue. Believe it's been rate limited

**Comment by oNIenSis** [comment]
I'm wondering if it could be the search json that feeds into graphql - maybe they've changed the schema? I couldn't work out how to create a new query myself to test it

**Comment by hcoohb** [comment]
Arghh... same issue here...
Just when I was starting to get everything working

**Comment by oNIenSis** [comment]
OK it's not the graphql query, I tested with a simple query and got the same errors. I think they might have implemented something to block this method :(

**Comment by talhaty** [comment]
same issue :(

**Comment by talhaty** [comment]
is there any other way for scrapping this site? I tried to do it with selenium but it doesn't work.

**Comment by BenGardiner123** [comment]
The error message "JSONDecodeError: Expecting value: line 1 column 1 (char 0)" indicates that the API response is empty or does not contain valid JSON data. This can happen if the API request did not receive a response from the server or if the server returned an unexpected response.

**Comment by sadrossa** [comment]
I'm no expert & am trying to learn the rope
 ... I've added in some exception handling 
... HTTP error occurred: 429 Client Error: Too Many Requests for url: https://lexa.realestate.com.au/graphql
[]

**Comment by muhashi** [comment]
Looks like they've added anti-scraping protections to the API, with Kasada it looks like? (based on the http header `x-kpsdk-ct: 0921380abc...`)

I haven't tried getting around it, but apparently it's a bit difficult to get around. If you still really need realestate.com.au data, [here is a blog post that gives some suggestions on how to get around Kasada](https://hackernoon.com/how-to-scrape-kasada-protected-websites) (but it may be out of date, I haven't tested)

**Comment by intothevoid** [comment]
> I'm no expert & am trying to learn the rope ... I've added in some exception handling ... HTTP error occurred: 429 Client Error: Too Many Requests for url: https://lexa.realestate.com.au/graphql []

Stepped through the code today. I am getting the same error, looks like scrapping protection of some kind?

**Comment by arbusam** [comment]
I'm getting the same issue and I just found this issue after trying to debug this myself thinking it was a problem on my end :| Has anyone found a fix/workaround yet?

**Comment by Shevchenkojjj** [comment]
yes same here. looks like it's banned

**Comment by grebfar** [comment]
This package is no longer functional.

**Comment by mahezsh** [comment]
Did someone find a way around this?

**Comment by CharlieFng** [comment]
Any solutions or update for this issue?
